apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: harbor-operator
  template:
    metadata:
      labels:
        name: harbor-operator
    spec:
      containers:
        - name: harbor-operator
          # Replace this with the built image name
          image: harbor-operator:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /tmp
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "harbor-operator"
      volumes:
        - name: config
          configMap:
            name: harbor-operator
            items:
              - key: config.yaml
                path: config.yaml

